export const religion = [
  "Ziemia jest dyskiem z kopułą! Jesteśmy w centrum wszechświata. Słońce jest w środku kopuły i porusza się siłą magii. Antarktydy pilnuje wojsko. Wsyzstkie dowody są na jutuba. Arktyka jest w środku dysku bo tak pasuje. Jak polecisz za wysoko to uderzysz kopułę. Ziemia jest płaska lemingu. To tylko teoria.",
  "Od żydów w łapę dostałeś? Ile ci dali masoni? Za Antarktydą jest mnóstwo ziemi nieodkrytej ale oni niechcą żebyś o tym wiedział. Gwiazdy są małe, przecież widać. Istnieje tylko jedno pełnoklatkowe zdjęcie ziemi. Na zdjeciach ziemi nie ma gwiazd!",
  "Wróżenie z fusów. Słońce oświetla księzyc pod niwełaściwym kątem. Wierząc w układ słoneczny czcisz demony.",
  "Bóg umiescił słońce i księżyc na tej polerowanej stali. Schowajscie te gupiomondre schematy, ja tu oczami widzę! Ezoteryka i metafizyka też mają swoje sukcesy! Płaska ziemia pojawiła się we właściwym momencie żeby uświadomić ludziom że jesteśmy okłamoywani. Za szerzenie kuloziemsktwa płacą masoni, żydzi, NASA i ESA. Agenci zwalczają ideę płaskiej ziemi bo promują heliocentryzm, hell to jest piekło więc promują piekłocentryzm Kopernika. Kopernik był masonem i iluminatą, jego teoria jest z kościoła, tylko że zrobili oni taką ściemę że go zwalczają. You spin me right round, baby right round. Skyfun - wiatrak nieba, ważny agent i iluminata, tylko rogów jemu brakuje.",
  "Słońce i księżyc magicznie latają i poruszają się siłą magii. Słońce spiskuje. Kopuła jest ze stali. Kopuła jest z cegieł. Nad kopułą jest ocean i niebiosa. Obućcie się!",
  "Satelity. Sat pochodzi od saturna i od satanizmu, sataniści są wyznawcami saturna, elity to władza. Rządzą nami satanistyczne elity. Niby skąd to wiedzą. Twarz Boga jest wyrysowana na płaskiej ziemi!",
  "Na dysku ziemi nie ma drzew, to co widzicie to nie są drzewa tylko nędzne chwasty. Góry to skamieniałe pnie drzew. Były to giganty wysokości 100 kilometrów łączące ziemię z niebem i aniołami. Które zostały wyrwane i ścięte przez tajemnicze złe siły, a wtedy spadł poziom tlenu i daliśmy oszukać się że ziemia jest kulą. System wykonuje wyroki śmierci które można przeżyć. Agenci dążą do ośmieszenia nas. Ci mondrale są po wpłyem prania mózgów nie my. To zorganizowana akcja ośmieszania za wszelką cenę ludzi uczciwych którrzy wskazują na prawde o kształcie ziemi. Oni sieją kłamstwa ponieważ oni to nasienie ojca kłamstwa czyli szatana. To wysoce nieuczciwi ludzie z obozu nasienia węża. Świat szatana zaatakował Boga. Płaska ziemia rozbija w drobny pył ich szatański niepochamowany pęd aby nas wszystkich zniszczyć.",
  "Chcą zrobić z nas ludzi niespełna rozumu. Kłamiliwym elitkom robi się gorąco pod kołnierzykami, ponieważ płaska ziemia to dowód ich satanizmu, ich stosowania doktryn lucyferiańskich. Ewolucja, ogrom wszechświata, to wszystko po to aby odwieźć człowieka od Boga.",
];
export const science = [
  "Ziemia jest dyskiem z kopułą. Grawitacja nie istnieje a nas do ziemi przyciąga elektromagnetyzm. Nigdy nie lataliśmy w kosmos. Satelity nie istnieją. Księżyc świeci własnym światłem które ochładza przedmioty. Waszystko to spisek. Żyroskopy w samolotach się nie obracają, nie muszą bo ziemia jest płaska. Samoloty lecące na kulistej ziemi powinny obniżać co jakiś czas dziób, bo innaczej wylecą w kosmos. Wsyzstkie dowody są na jutuba.",
  "Ziemia wiruje więc na równiku powinno zalać lądy. Ziemia wiruje, układ słoneczny też wiruje oraz galaktyka też wiruje więc z połączenia tych trzech ruchów powinien wyjść totalny chaos! Nie warto ufać wyliczeniom i teoriom, wszystko trzeba brać na własny chłopski rozum. Przedmioty za horyzontem nie znikają, tylko zasłoniły je fale. Jeśli ziemia jest kulista to długie rzeki takie jak Nil płyną pod górę więc ziemia jest płaska! NASA modyfikuje zdjęcia, to tajne!",
  "Ziemia jest płaska! Skończ z tymi bzdurami, pomyśl chwilę samodzielnie! Ale NASA ci nastukała w główce. Twoja wiedza opiera się tylko na podręcznikach!",
  "Szkolne wypociny! NASA w photoshope dokleja ziemię. Co ty chcesz sprawdzać? Przecież wszystko w internecie jest, myślisz że ludzie kłamią albo głupi są? To perspektywa. Słońce nie zachodzi. Skąd niby to wiedzą? Obiekty znikają od spodu przez perspektywę. Nie sądzę aby loty blisko antarktydy latały. Bo ktoś widział cąły niezbadany kontynent za antarktydą.",
  "USA i ZSRR strzelały do kopuły z bomb atomowych żeby sprawzić jak jest wysoko. Grzyb atomowy to dowód rozpłaszczania się eksploacji na suficie świata. Jakby ziemia się kręciłą 1000 kilometrów na godzinę to chyba bym to czuł, a przecież czuję zmysłami że obrotu nie ma. Samolot powinien odczuć super przyspieszenie jak wylonduje na równiku. Grawitacja to efekt gęstości ciał. Dysk nieustannie przyśpiesza w górę z przeciążeniem 1G.",
  "Ziemia rotuje i stąd jest grawitacja. Czasami krzywizna jet mała a nie może być więc to kłamstwo. Zakrzywiony horyzont to rybie oko, a są zdjęcia bez krzywizny.",
  "Słońce znajduje się 4800 km nad dyskiem i ma średnicę 54 kilometry. Promienie słońca stykają się nad chmurami a to oznacza że słońce znajduje się tuż nad chmurami. Słońce nie zachodzi. Słońce pomniejsza się przez perspektywę. Słońce znika jako efekt istnienia przeszkód na horyzoncie na przykład gór. Księzyc też jest płaski. Absolute Proof... 1000% Proof... Gwiazda polarna jest na środku kopuły i wszystkie inne kręcą się wokół niej.",
  "Gwiazda polarna jest widoczna na drugiej półkuli, ale czasami nie poniważ perspektywa. Nie pojedziemy na antarktydę bo nam nie wolno. Wszystkie gwiazdy, planety i księżyce to zjawiska bliskie i lokalne. Istnieje zorganizowana sieć blokad które nie pozwalają nam pójść na antarktydę. Fikcja, grafika komputerowa, jesteśmy okłamywani, ziemia jest płaska. Mierzenie lotu poziomicą.",
  "Istnieje dół kosmposu. Róbcie swój własny research. Nam się zmieniło, kopuła to nie kopuła, to niski sufit.",
  "To wielkie tajemnice natury. Atmosfera powinna zostać wessana przez próżnię. Rzeki płynące na północ płyną pod górę, a rzeki nie mogą płynąć pod górę więc ziemia jest płaska. Woda szuka poziomu. Zdjęcia są sfałszowane. NASA wyświetla ślady meteorów na kopule a kratery można wykopać. Dwa ośrodki o różnym ciśnieniu nie mogą istnieć koło siebie bez bariery więc jak kosmos styka się z atmosferą? Na ziemi są przedmioty które widać za kulą słońca. PRPRPR... hehehe... no.",
  "Słońce pływa sobie wśród chmur. Po co coś badać jak wszystkie dowody są na youtube. NASA kłamie bo NASA kłamie. Wszystko to fejk. To refrakcja. To fatamorgana. Inne planety w przeciwieństwie do ziemi zostały zaobserwowane jako okrągłe.",
];
